project:
  type: website

website:
  title: "Richard Hanna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: data_science.qmd
        text: Data Science
    right: 
      - href: https://github.com/rsh52
        icon: "github"
      - href: https://www.linkedin.com/in/richard-hanna-ms-0164162a/
        icon: "linkedin"
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

